# Platform-specific data file for chezmoi
# Data file processed before .chezmoi.toml

# User preferences
[preferences]
    shell = "zsh"
    editor = "zed"
    terminal = "ghostty"

# Development tools configuration
[dev]
    use_docker = true
    use_kubernetes = true
    use_python = true
    use_node = true
    use_rust = true
    use_go = true
    use_ai_tools = true
    use_helix = false

# Platform-specific configuration
[platform]
    os = "macos"
    package_manager = "brew"

# Paths
[paths]
    brew_bin = "/opt/homebrew/bin/brew"
    brew_prefix = "/opt/homebrew"
