# Chezmoi configuration file
# Documentation: https://www.chezmoi.io/reference/configuration-file/

# Source directory is automatically detected from .chezmoiroot

# Working tree settings
[edit]
    # Command to use for editing files - using Zed as primary IDE
    command = "zed"
    args = ["--wait"]

# Git settings
[git]
    # Auto-add files when they change
    autoAdd = true
    # Auto-commit changes
    autoCommit = true
    # Auto-push commits
    autoPush = false

# Merge settings
[merge]
    # Command to use for merging - using Zed as primary IDE
    command = "zed"
    args = ["--wait", "--merge", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

# Diff settings
[diff]
    # Use delta for diffs if available
    command = "delta"
    args = ["{{ .Destination }}", "{{ .Target }}"]

# Data for templates - this can be overridden by .chezmoidata files
[data]
    # Personal information
    name = "Jack Matanky"
    email = "JackMatanky@gmail.com"
    
    # System preferences (must match template variable references)
    [data.preferences]
        shell = "zsh"
        editor = "zed"
        terminal = "ghostty"
    
    # Theme configuration
    [data.theme]
        colorscheme = "catppuccin_latte"
        primary_color = "#1e66f5"
        secondary_color = "#7287fd"
        accent_color = "#40a02b"
    
    # Development tools
    [data.dev]
        use_docker = true
        use_kubernetes = true
        use_python = true
        use_node = true
        use_rust = true
        use_go = true
        # AI/ML tools
        use_ai_tools = true
    
    # Package managers
    [data.packages]
        use_homebrew = true
        use_cargo = true
        use_npm = true
        use_flatpak = true
    
    # OS-specific features (use .chezmoi.os in templates instead)
    [data.os]
        # These will be available in templates as .os.current, .os.arch, etc.
        # Use {{ .chezmoi.os }} and {{ .chezmoi.arch }} in templates for OS detection

# Age encryption (uncomment and configure if you want to use encrypted files)
# [age]
#     identity = "~/.config/chezmoi/key.txt"
#     recipient = "age1..."

# Hooks - run commands at different stages
[hooks.read-source-state.pre]
    command = ".local/share/chezmoi/.chezmoiscripts/check-deps.sh"

# Template options
[template]
    options = ["missingkey=error"]

# Scripts
[scriptEnv]
    CHEZMOI_OS = "{{ .chezmoi.os }}"
    CHEZMOI_ARCH = "{{ .chezmoi.arch }}"
    HOME = "{{ .chezmoi.homeDir }}"
