# Chezmoi data file for template variables
# This file allows you to define variables that can be used in templates
# and can be overridden per-machine using .chezmoidata.yaml files

# Personal information
name: "Jack Matanky"
email: "JackMatanky@gmail.com"
github_username: "JackMatanky"

# System preferences
shell: "zsh"
editor: "code"
terminal: "ghostty"

# Development tools configuration
dev_tools:
  python:
    enabled: true
    version: "3.11"
    use_pyenv: true
  node:
    enabled: true
    use_nvm: true
  rust:
    enabled: true
    use_rustup: true
  go:
    enabled: true
  docker:
    enabled: true
  kubernetes:
    enabled: true

# Package manager preferences
package_managers:
  homebrew:
    enabled: true
    tap_fonts: true
    tap_casks: true
  cargo:
    enabled: true
  npm:
    enabled: true
  flatpak:
    enabled: true

# Application preferences
applications:
  espanso:
    enabled: true
    config_name: "default"
  tmux:
    enabled: true
    start_on_login: false
  starship:
    enabled: true
  zellij:
    enabled: true
  helix:
    enabled: true
  nvim:
    enabled: true
    distribution: "lazyvim"

# Theme preferences
themes:
  color_scheme: "catppuccin"
  variant: "macchiato"
  
# Directories
directories:
  projects: "~/Projects"
  dotfiles: "~/.config"
  scripts: "~/.local/bin"

# Feature flags - can be toggled per machine
features:
  use_age_encryption: false
  auto_install_packages: true
  setup_development_env: true
  configure_shell_integrations: true
  setup_git_hooks: false
