# -----------------------------------------------------------------------------
# Filename: ~/.local/share/chezmoi/.pre-commit-config.yaml
# Docs: https://pre-commit.com/
# Description: Pre-commit hooks for code quality, notebook sync, and hygiene
# -----------------------------------------------------------------------------

repos:
  # -------------------- Pre-Commit Hooks -------------------- #
  # Docs: https://github.com/pre-commit/pre-commit-hooks/tree/main/pre_commit_hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: Prevent Large Files in Git
        args: ["--maxkb=500"]
      - id: check-executables-have-shebangs
        name: Ensure Executable Scripts Have Shebangs
      - id: check-merge-conflict
        name: Detect Merge Conflict Markers
      - id: check-json
        name: Validate JSON Files
        exclude: ".tmpl$|(^|/)\\.chezmoitemplates/|(zed|vscode)/.*.json|cspell\\.json"
      - id: check-toml
        name: Validate TOML Files
        exclude: ".tmpl$|(^|/)\\.chezmoitemplates/"
      - id: check-yaml
        name: Validate YAML Files
        exclude: ".tmpl$|(^|/)\\.chezmoitemplates/"
      - id: detect-private-key
        name: Detect Accidental Private Keys
      - id: end-of-file-fixer
        name: Ensure Final Newline
      - id: mixed-line-ending
        name: Fix Mixed Line Endings
        args: [--fix=lf]
      - id: trailing-whitespace
        name: Remove Trailing Whitespace

  # ---------------------- Gitleaks Scan --------------------- #
  # Docs: https://github.com/gitleaks/gitleaks?tab=readme-ov-file#pre-commit
  - repo: "https://github.com/gitleaks/gitleaks"
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: gitleaks (secrets scan)
        # args: ["--no-banner", "--config=.gitleaks.toml"]
