#------------------------------------------------------------------------------
# Filename: ~/.config/espanso/match/wezterm.yml
#
# Espanso Docs: https://espanso.org/docs/
#------------------------------------------------------------------------------
---
filter_class: ^org\.wezfurlong\.wezterm$

paste_shortcut: CTRL+SHIFT+V
