#--------------------------------------------------------------------
# Filename: ~/dotfiles/helix/config.toml
#
# Helix Docs: https://docs.helix-editor.com/languages.html
#--------------------------------------------------------------------

# >>> Language Servers <<<

# --- Python ---
# PyLSP
[language-server.pylsp]
command = "pylsp"

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true, ignore = ["E501", "E305", "E302", "W293"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
pylsp-mypy = { enabled = true },
pylsp-rope = { enabled = true },
python-lsp-ruff = { enabled = true }

[[language]]
name = "python"
file-types = ["py"]
shebangs = ["python"]
language-servers = [{name = "pylsp"}]
formatter = {command = "ruff", args = ["--quiet", "-"]}
auto-format = true
indent = {tab-width = 4, unit = "    "}

# --- HTML ---
# VS Code HTML Language Server
[language-server.vscode-html-language-server]
command = "vscode-html-language-server"

# EMMET-LSP / github.com/olrtg
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
auto-format = true
language-servers = [ "vscode-html-language-server", "emmet-lsp" ]
formatter = { command = "prettier", args = ["--parser", "html"]}
file-types = ["html", "gohtml"]
indent = {tab-width = 2, unit = "  "}

# --- CSS ---
# VS Code CSS Language Server
[language-server.vscode-css-language-server]
command = "vscode-css-language-server"

[[language]]
name = "css"
auto-format = true
language-servers = [{name = "vscode-css-language-server"}]
formatter = { command = "prettier", args = ["--parser", "css"]}
indent = {tab-width = 2, unit = "  "}

# --- JavaScript and TypeScript ---
# TypeScript Language Server
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

# JavaScript
[[language]]
name = "javascript"
auto-format = true
language-servers = [{name = "typescript-language-server"}]
formatter = { command = "prettier", args = ["--parser", "typescript"]}
indent = {tab-width = 2, unit = "  "}

# TypeScript
[[language]]
name = "typescript"
auto-format = false
language-servers = [{name = "typescript-language-server"}]
indent = {tab-width = 4, unit = "    "}

# --- JSON ---
# VS Code JSON Language Server
[language-server.vscode-json-language-server]
command = "vscode-json-language-server"

[[language]]
name = "json"
auto-format = true
language-servers = [{name = "vscode-json-language-server"}]
formatter = { command = "prettier", args = ["--parser", "json"]}
indent = {tab-width = 2, unit = "  "}

# --- TOML ---
[[language]]
name = "toml"
auto-format = true
# https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml
formatter = { command = "prettier", args = ["--parser", "toml"] }

# --- Markdown ---
# Marksman
[language-server.marksman]
command = "marksman"

[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format = true
formatter = { command = "markdownlint", args = ["--fix"] }

[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format = false
formatter = { command = "prettier", args = ["--parser", "markdown"] }
