# ----------------------------------------------------------------------------
#  Filename: ~/.config/marimo/marimo.toml
#  Docs: https://docs.marimo.io
#  Source: https://github.com/marimo-team/marimo/blob/main/marimo/_config/config.py
# ----------------------------------------------------------------------------


[completion]
activate_on_typing = true
copilot = false
# codeium_api_key = ""
# api_key = ""
# model = ""
# base_url = ""

[display]
theme = "light"                      # Options: "light", "dark", "system"
code_editor_font_size = 14
cell_output = "above"               # Options: "above", "below"
default_width = "medium"            # Options: "normal", "compact", "medium", "full", "columns"
dataframes = "rich"                 # Options: "rich", "plain"
default_table_page_size = 10
# custom_css = ["path/to/custom.css"]

[formatting]
line_length = 79

[keymap]
preset = "default"
# vimrc = "path/to/vimrc"
# [keymap.overrides]
# "run-cell" = "Ctrl+Enter"

[runtime]
auto_instantiate = true
auto_reload = "autorun"             # Options: "off", "lazy", "autorun"
reactive_tests = true
on_cell_change = "autorun"          # Options: "lazy", "autorun"
watcher_on_save = "lazy"            # Options: "lazy", "autorun"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
# pythonpath = ["src", "lib"]
# dotenv = [".env"]

[save]
autosave = "after_delay"            # Options: "off", "after_delay"
autosave_delay = 1000
format_on_save = false

[package_management]
manager = "uv"                      # Options: "pip", "rye", "uv", "poetry", "pixi"

[server]
browser = "default"
follow_symlink = false

[language_servers.pylsp]
enabled = false
# enable_mypy = true
# enable_ruff = true
# enable_flake8 = false
# enable_pydocstyle = false
# enable_pylint = false
# enable_pyflakes = false

[snippets]
# custom_paths = ["snippets/"]
include_default_snippets = true

# [ai]
# rules = "Keep answers clear and concise"
# max_tokens = 1000
# [ai.open_ai]
# api_key = "sk-..."
# model = "gpt-4"
# base_url = "https://api.openai.com/v1"
# ssl_verify = true
# ca_bundle_path = ""
# client_pem = ""
#
# [ai.anthropic]
# api_key = "..."
#
# [ai.google]
# api_key = "..."

# [diagnostics]
# enabled = true

# [datasources]
# auto_discover_schemas = true
# auto_discover_tables = true
# auto_discover_columns = true

# [experimental]
# enable_feature_x = true
