# Repository and URL configuration
# Static information about repositories, URLs, and external resources

[repositories]
[repositories.dotfiles]
github = "https://github.com/JackMatanky/dotfiles.git"
description = "Personal dotfiles and system configuration"

[repositories.obsidian]  
gitlab = "https://gitlab.com/JackMatanky/obsidian_vault.git"
description = "Personal knowledge base and notes"

# Useful development URLs
[urls]
[urls.documentation]
chezmoi = "https://www.chezmoi.io/"
homebrew = "https://brew.sh/"
rust = "https://www.rust-lang.org/"
golang = "https://golang.org/"

[urls.package_registries]
crates_io = "https://crates.io/"
npm = "https://www.npmjs.com/"
pypi = "https://pypi.org/"
homebrew_formulae = "https://formulae.brew.sh/"

[urls.tools]
github_cli = "https://cli.github.com/"
just = "https://just.systems/"
starship = "https://starship.rs/"

# API endpoints (without secrets)
[apis]
[apis.github]
base_url = "https://api.github.com"
graphql = "https://api.github.com/graphql"

[apis.gitlab]
base_url = "https://gitlab.com/api/v4"
