# Filename: ~/dotfiles/tmux/tmux.conf
#
# GitHub Repo: https://github.com/tmux/tmux


# --- General Settings ---

# Reload config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Set default shell to nushell
set-option -g default-shell /opt/homebrew/bin/nu

# Set default terminal and terminal overrides
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Set prefix to Ctrl+a and enable mouse mode
set -g prefix C-a
set -g mouse on

# Set status bar position to top
set-option -g status-position top


# --- Plugins ---

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'


# --- Catppuccin Theme ---

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"


# --- Status Bar ---

# Set status line lengths
set -g status-right-length 100
set -g status-left-length 100

# Configure status left
set -g status-left ""

# Configure status right with Catppuccin modules
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"


# --- Plugin Manager ---

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
